# vim:ft=kitty
## name: Carbon Mochi
## license: MIT
## author: Carbon Theme

background #0a0a0a
foreground #d9d9d9
selection_background #2f3237
selection_foreground #d9d9d9
url_color #6ebad7
cursor #d9d9d9
cursor_text_color #0a0a0a

# Tabs
active_tab_background #ff669e
active_tab_foreground #0a0a0a
inactive_tab_background #2f3237
inactive_tab_foreground #56575d

# Windows
active_border_color #ff669e
inactive_border_color #2f3237

# normal
color0 #0a0a0a
color1 #c85e60
color2 #a3c679
color3 #d5b05f
color4 #6a90d0
color5 #a178c4
color6 #6ebad7
color7 #d9d9d9

# bright
color8 #45454a
color9 #c85e60
color10 #a3c679
color11 #d5b05f
color12 #6a90d0
color13 #a178c4
color14 #6ebad7
color15 #ffffff

# extended colors
color16 #cd775c
color17 #c85e60
