# vim:ft=kitty
## name: Carbon Darkmatter
## license: MIT
## author: Carbon Theme

background #121113
foreground #c1c1c1
selection_background #222222
selection_foreground #c1c1c1
url_color #5f8787
cursor #c1c1c1
cursor_text_color #121113

# Tabs
active_tab_background #e78a53
active_tab_foreground #121113
inactive_tab_background #222222
inactive_tab_foreground #888888

# Windows
active_border_color #e78a53
inactive_border_color #222222

# normal
color0 #121113
color1 #e78a53
color2 #5f8787
color3 #fbcb97
color4 #5f8787
color5 #e78a53
color6 #5f8787
color7 #c1c1c1

# bright
color8 #333333
color9 #e78a53
color10 #5f8787
color11 #fbcb97
color12 #5f8787
color13 #e78a53
color14 #5f8787
color15 #c1c1c1

# extended colors
color16 #e78a53
color17 #e78a53
