# vim:ft=kitty
## name: Carbon Caffeine
## license: MIT
## author: Carbon Theme

background #111111
foreground #eeeeee
selection_background #222222
selection_foreground #eeeeee
url_color #ffe0c2
cursor #eeeeee
cursor_text_color #111111

# Tabs
active_tab_background #ffe0c2
active_tab_foreground #111111
inactive_tab_background #222222
inactive_tab_foreground #b4b4b4

# Windows
active_border_color #ffe0c2
inactive_border_color #201e18

# normal
color0 #111111
color1 #e54d2e
color2 #393028
color3 #ffe0c2
color4 #1d4ed8
color5 #ffe0c2
color6 #ffe0c2
color7 #eeeeee

# bright
color8 #2a2a2a
color9 #e54d2e
color10 #393028
color11 #ffe0c2
color12 #1d4ed8
color13 #ffe0c2
color14 #ffe0c2
color15 #eeeeee

# extended colors
color16 #ffe0c2
color17 #e54d2e
